WebApplication/Models/ChuongTrinhDaoTao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhDaoTao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinhDaoTao()
        {
            this.KhoiKienThucs = new HashSet<KhoiKienThuc>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public Nullable<int> ID_Khoa { get; set; }
        public Nullable<int> ID_HocKyBatDau { get; set; }
    
        public virtual HocKyDaoTao HocKyDaoTao { get; set; }
        public virtual KhoaDaoTao KhoaDaoTao { get; set; }
        public virtual NganhDaoTao NganhDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoiKienThuc> KhoiKienThucs { get; set; }
    }
}

WebApplication/Areas/Faculty/Controllers/ChuongTrinhDaoTaoController.cs
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Areas.Faculty.Controllers
{
    public class ChuongTrinhDaoTaoController : Controller
    {
        private Cap24 db = new Cap24();
        public string KiemTraHK(int HK)
        {
            string ListLoi = "";
            if (HK < 100 || HK >= 1000)
            {
                ListLoi += "<p> Học kỳ phải có 3 chữ số </p>";
            }
            var listDBHK = db.HocKyDaoTaos.ToList();
            var listHK = new List<string>();
            foreach (var item in listDBHK)
            {
                listHK.Add(item.HocKy.ToString());
            }
            if (CheckTonTai(HK.ToString(), listHK))
            {
                ListLoi += "<p> Học kỳ đào tạo đã tồn tại trong hệ thống, vui lòng thử lại!</p>";
            }
            return ListLoi;
        }
        public ActionResult ListHocKyDT()
        {
            return View(db.HocKyDaoTaos.ToList());
        }

        public ActionResult TaoMoiHocKy()
        {
            return View();
        }
        // POST: Faculty/Nganh/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TaoMoiHocKy(HocKyDaoTao hocKyDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraHK(hocKyDaoTao.HocKy);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;
                    return RedirectToAction("TaoMoiHocKy");
                }
                db.HocKyDaoTaos.Add(hocKyDaoTao);
                db.SaveChanges();
                TempData["ThongBao"] = "Tạo mới học kỳ thành công";
                return RedirectToAction("ListHocKyDT");
            }
            return View(hocKyDaoTao);
        }

        public ActionResult SuaHocKyDT(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HocKyDaoTao hocKyDaoTao = db.HocKyDaoTaos.Find(id);
            if (hocKyDaoTao == null)
            {
                return HttpNotFound();
            }
            return View(hocKyDaoTao);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaHocKyDT(HocKyDaoTao hocKyDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraHK(hocKyDaoTao.HocKy);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;
                    return RedirectToAction("SuaHocKyDT", new { id = hocKyDaoTao.ID });
                }
                db.Entry(hocKyDaoTao).State = EntityState.Modified;
                db.SaveChanges();
                TempData["ThongBao"] = "Sửa học kỳ thành công";
                return RedirectToAction("ListHocKyDT");
            }
            return View(hocKyDaoTao);
        }

        public ActionResult XoaHocKyDT(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HocKyDaoTao hocKyDaoTao = db.HocKyDaoTaos.Find(id);
            if (hocKyDaoTao == null)
            {
                return HttpNotFound();
            }
            return View(hocKyDaoTao);
        }

        // POST: Faculty/NganhDaoTaos/Delete/5
        [HttpPost, ActionName("XoaHocKyDT")]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanXoaHocKyDT(int id)
        {
            HocKyDaoTao hocKyDaoTao = db.HocKyDaoTaos.Find(id);
            db.HocKyDaoTaos.Remove(hocKyDaoTao);
            db.SaveChanges();
            TempData["ThongBao"] = "Xóa học kỳ thành công";
            return RedirectToAction("ListHocKyDT");
        }

        public string KiemTraKhoa(int khoa)
        {
            string ListLoi = "";
            if (khoa <= 0)
            {
                ListLoi += "<p> Khóa đào tạo phải là số nguyên dương lớn hơn 0, khóa đào tạo bạn nhập là: " + khoa + "</p>";
            }
            var listDBKhoa = db.KhoaDaoTaos.ToList();
            var listKhoa = new List<string>();
            foreach (var item in listDBKhoa)
            {
                listKhoa.Add(item.Khoa.ToString());
            }
            if (CheckTonTai(khoa.ToString(), listKhoa))
            {
                ListLoi += "<p> Khóa đào tạo đã tồn tại trong hệ thống, vui lòng thử lại!</p>";
            }
            return ListLoi;
        }
        public ActionResult ListKhoaDT()
        {
            return View(db.KhoaDaoTaos.ToList());
        }

        public ActionResult TaoMoiKhoa()
        {
            return View();
        }
        // POST: Faculty/Nganh/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TaoMoiKhoa(KhoaDaoTao khoaDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraKhoa(khoaDaoTao.Khoa);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;
                    return RedirectToAction("TaoMoiKhoa");
                }
                db.KhoaDaoTaos.Add(khoaDaoTao);
                db.SaveChanges();
                TempData["ThongBao"] = "Tạo mới khóa thành công";
                return RedirectToAction("ListKhoaDT");
            }
            return View(khoaDaoTao);
        }

        public ActionResult SuaKhoaDT(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhoaDaoTao khoaDaoTao = db.KhoaDaoTaos.Find(id);
            if (khoaDaoTao == null)
            {
                return HttpNotFound();
            }
            return View(khoaDaoTao);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaKhoaDT(KhoaDaoTao khoaDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraKhoa(khoaDaoTao.Khoa);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;
                    return RedirectToAction("SuaKhoaDT", new { id = khoaDaoTao.ID });
                }
                db.Entry(khoaDaoTao).State = EntityState.Modified;
                db.SaveChanges();
                TempData["ThongBao"] = "Sửa khóa thành công";
                return RedirectToAction("ListKhoaDT");
            }
            return View(khoaDaoTao);
        }

        public ActionResult XoaKhoaDT(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhoaDaoTao khoaDaoTao = db.KhoaDaoTaos.Find(id);
            if (khoaDaoTao == null)
            {
                return HttpNotFound();
            }
            return View(khoaDaoTao);
        }

        // POST: Faculty/NganhDaoTaos/Delete/5
        [HttpPost, ActionName("XoaKhoaDT")]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanXoaKhoaDT(int id)
        {
            KhoaDaoTao khoaDaoTao = db.KhoaDaoTaos.Find(id);
            db.KhoaDaoTaos.Remove(khoaDaoTao);
            db.SaveChanges();
            TempData["ThongBao"] = "Xóa khóa thành công";
            return RedirectToAction("ListKhoaDT");
        }

        public string KiemTraNganh(string nganh)
        {
            string ListLoi = "";

            if (nganh.Length > 100)
            {
                ListLoi += "<p> Ngành đào tạo không được lớn hơn 100 ký tự, số ký tự của ngành đào tạo bạn nhập là: " + nganh.Length + "</p>";
            }
            var listDBNganh = db.NganhDaoTaos.ToList();
            var listNganh = new List<string>();
            foreach (var item in listDBNganh)
            {
                listNganh.Add(item.Nganh);
            }
            if (CheckTonTai(nganh, listNganh))
            {
                ListLoi += "<p> Ngành đào tạo đã tồn tại trong hệ thống, vui lòng thử lại!</p>";
            }
            return ListLoi;
        }

        public ActionResult ListNganhDT()
        {
            return View(db.NganhDaoTaos.ToList());
        }

        public ActionResult TaoMoiNganh()
        {
            return View();
        }
        // POST: Faculty/Nganh/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TaoMoiNganh(NganhDaoTao nganhDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraNganh(nganhDaoTao.Nganh);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;
                    return RedirectToAction("TaoMoiNganh");
                }
                db.NganhDaoTaos.Add(nganhDaoTao);
                db.SaveChanges();
                TempData["ThongBao"] = "Tạo mới ngành thành công";
                return RedirectToAction("ListNganhDT");
            }
            return View(nganhDaoTao);
        }

        public ActionResult SuaNganhDT(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NganhDaoTao nganhDaoTao = db.NganhDaoTaos.Find(id);
            if (nganhDaoTao == null)
            {
                return HttpNotFound();
            }
            return View(nganhDaoTao);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaNganhDT(NganhDaoTao nganhDaoTao)
        {
            if (ModelState.IsValid)
            {
                var ListLoi = KiemTraNganh(nganhDaoTao.Nganh);
                if (ListLoi != "")
                {
                    TempData["Alert"] = ListLoi;

WebApplication/Areas/Faculty/Views/ChuongTrinhDaoTao/ChiTietCTDaoTao.cshtml
@model WebApplication.Models.ChuongTrinhDaoTao

@{
    ViewBag.Title = "ChiTietCTDaoTao";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
    int STT = 0;
    
}
<style>
    th, tr {
        color: black;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title" style="font-family:Roboto">&emsp;CHƯƠNG TRÌNH ĐÀO TẠO KHÓA @Model.KhoaDaoTao.Khoa NGÀNH @Model.NganhDaoTao.Nganh.ToUpper()</h4>
            <div class="page-title-right" id="btnFunction">
                <form>
                    <input type="number" value="@Model.ID" name="@Model.ID" hidden />
                    <input type="file" id="file" style="display:none;" />
                    <button type="button" id="button" name="button" value="Upload" class="btn btn-secondary btn-rounded" data-toggle="modal" data-target="#exampleModal">
                        <i class="mdi mdi-microsoft-excel"></i> Chỉnh sửa
                    </button>
                    &ensp;
                    <button type="submit" id="button" name="button" value="Export" class="btn btn-secondary btn-rounded" formaction="@Url.Action("XuatCTDaoTao", new { id = Model.ID })">
                        <i class="mdi mdi-microsoft-excel"></i> Xuất excel
                    </button>

                    &ensp;
                    <button type="submit" id="button" name="button" value="Upload" class="btn btn-secondary btn-rounded" onclick="PrintCTDT()">
                        <i class="mdi mdi-cloud-print-outline"></i> In
                    </button>
                    &ensp;
                    <button type="button" id="button" name="button" value="Xóa" class="btn btn-secondary btn-rounded " data-toggle="modal" data-target="#modelId">
                        <i class="mdi mdi-delete-outline"></i> Xóa
                    </button>
                </form>
                <!-- Modal -->
                <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" style="font-family: Roboto;">Xóa chương trình đào tạo</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid">
                                    Xác nhận xóa chương trình đào tạo Ngành @Model.NganhDaoTao.Nganh - Khóa @Model.KhoaDaoTao.Khoa
                                </div>
                                <label for="recipient-name" class="col-form-label">Nhập "Ngành @Model.NganhDaoTao.Nganh - Khóa @Model.KhoaDaoTao.Khoa" để xác nhận xóa:</label>
                                <input type="text" class="form-control" id="TextXacNhan" onchange="GetText(this.value)" value="" placeholder="Ngành @Model.NganhDaoTao.Nganh - Khóa @Model.KhoaDaoTao.Khoa">
                                <input id="textXacNhan" value="Ngành @Model.NganhDaoTao.Nganh - Khóa @Model.KhoaDaoTao.Khoa" hidden />
                            </div>
                            <form>
                                <div class="modal-footer">
                                    <input type="number" value="@Model.ID" name="id" hidden />
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                    <button type="submit" id="XacNhanBtn" class="btn btn-primary" formaction=@Url.Action("XoaCTDT") disabled>Xóa</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel" style="font-family: Roboto;">Chỉnh sửa chương trình đào tạo</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                @using (Html.BeginForm("ChinhSuaCTDaoTao", "ChuongTrinhDaoTao", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    <input hidden type="number" name="CTDT" value="@Model.ID" />
                                    <input hidden type="text" name="Nganh" value="@Model.NganhDaoTao.Nganh" />
                                    <input hidden type="text" name="Khoa" value="@Model.KhoaDaoTao.Khoa.ToString()" />
                                    <input hidden type="text" name="HK" value="@Model.HocKyDaoTao.HocKy.ToString()"/>
                                    <div class="file-upload-wrapper">
                                        <div class="file-upload-wrapper">
                                            <input id="excel_file" type="file" name="UploadedFile" class="dropify" accept=".xls,.xlsx" onclick="Clearform()" />
                                        </div>
                                        <div id="excel_data" class="table-responsive"></div>
                                    </div>
                                    <div class="modal-footer">
                                        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Đóng" />
                                        <input type="submit" class="btn btn-primary" value="Tải lên" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script>
                $('#exampleModal').on('show.bs.modal', event => {
                    var button = $(event.relatedTarget);
                    var modal = $(this);
                });
                function GetText(val) {
                    var text = document.getElementById("textXacNhan").value;
                    if (val == text) {
                        document.getElementById("XacNhanBtn").disabled = false;
                    } else {
                        document.getElementById("XacNhanBtn").disabled = true;
                    }
                }

                function PrintCTDT() {
                    document.getElementById("btnFunction").style.display = "none";
                    window.print();
                    document.getElementById("btnFunction").style.display = "block";
                }
            </script>
        </div>
    </div>
</div>
<!-- end page title -->
@foreach (var khoikienthuc in ViewData["KhoiKienThuc"] as List<WebApplication.Models.KhoiKienThuc>)
{
    <div class="col-xl-12">
        <div class="card-box">
            <div class="dropdown float-right">
            </div>
            <h4 class="header-title mt-0 mb-3" style="font-family: Roboto;">@khoikienthuc.TenKhoiKienThuc</h4>

            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr style="background-color:lightblue">
                            <th>STT</th>
                            <th>Mã học phần</th>
                            <th>Tên học phần</th>
                            <th>Số tín chỉ</th>
                            <th>BB/TC</th>
                            <th>Tiên quyết</th>
                            <th>Học trước</th>
                            <th>Song hành</th>
                            <th>Học kỳ</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var hocphan in ViewData["HocPhan"] as List<WebApplication.Models.HocPhanDaoTao>)
                        {
                            if (hocphan.KhoiKienThuc.ID == khoikienthuc.ID)
                            {
                                <tr>
                                    @if (hocphan.ID_HocPhanTuChon == null)
                                    {
                                        STT++;
                                        <td>@STT</td>
                                    }
                                    else
                                    {
                                        <td></td>
                                    }
                                    <td>@hocphan.MaHocPhan</td>
                                    <td>@hocphan.TenHocPhan</td>
                                    <td>@hocphan.SoTinChi</td>
                                    @if (hocphan.ID_HocPhanTuChon == null)
                                    {
                                        <td>BB</td>
                                    }
                                    else
                                    {
                                        <td>TC</td>
                                    }
                                    <td>
                                        @foreach (var rangbuoc in ViewData["RangBuocHocPhan"] as List<WebApplication.Models.RangBuocHocPhan>)
                                        {
                                            if (rangbuoc.LoaiRangBuoc == "Tiên quyết" && rangbuoc.HocPhanDaoTao1.ID == hocphan.ID)
                                            {
                                                if (rangbuoc.HocPhanDaoTao.MaHocPhan != null)
                                                {
                                                    <p title="@rangbuoc.HocPhanDaoTao.TenHocPhan">
                                                        @rangbuoc.HocPhanDaoTao.MaHocPhan
                                                    </p>
                                                }
                                                else
                                                {
                                                    <p>
                                                        @rangbuoc.HocPhanDaoTao.TenHocPhan
                                                    </p>
                                                }
                                            }
                                        }
                                    </td>
                                    <td>
                                        @foreach (var rangbuoc in ViewData["RangBuocHocPhan"] as List<WebApplication.Models.RangBuocHocPhan>)
                                        {
                                            if (rangbuoc.LoaiRangBuoc == "Học trước" && rangbuoc.HocPhanDaoTao1.ID == hocphan.ID)
                                            {
                                                if (rangbuoc.HocPhanDaoTao.MaHocPhan != null)
                                                {
                                                    <p title="@rangbuoc.HocPhanDaoTao.TenHocPhan">
                                                        @rangbuoc.HocPhanDaoTao.MaHocPhan
                                                    </p>
                                                }
                                                else
                                                {
                                                    <p>
                                                        @rangbuoc.HocPhanDaoTao.TenHocPhan
                                                    </p>
                                                }
                                            }
                                        }
                                    </td>
                                    <td>
                                        @foreach (var rangbuoc in ViewData["RangBuocHocPhan"] as List<WebApplication.Models.RangBuocHocPhan>)
                                        {
                                            if (rangbuoc.LoaiRangBuoc == "Song hành" && rangbuoc.HocPhanDaoTao1.ID == hocphan.ID)
                                            {
                                                if (rangbuoc.HocPhanDaoTao.MaHocPhan != null)
                                                {
                                                    <p title="@rangbuoc.HocPhanDaoTao.TenHocPhan">
                                                        @rangbuoc.HocPhanDaoTao.MaHocPhan
                                                    </p>
                                                }
                                                else
                                                {
                                                    <p>
                                                        @rangbuoc.HocPhanDaoTao.TenHocPhan
                                                    </p>
                                                }
                                            }
                                        }
                                    </td>
                                    <td>&emsp;@hocphan.HocKy</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

WebApplication/Areas/Faculty/Views/ChuongTrinhDaoTao/DeleteNganh.cshtml
@model WebApplication.Models.Nganh

@{
    ViewBag.Title = "DeleteNganh";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
}

<h2>Xóa ngành @Model.TenNganh</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên ngành
        </dt>

        <dd>
            @Model.TenNganh
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="bbtn btn-secondary btn-rounded" /> |
            @Html.ActionLink("Trở về", "IndexNganh")
        </div>
    }
</div>

WebApplication/Areas/Faculty/Views/ChuongTrinhDaoTao/ListCTDaoTao.cshtml
@model IEnumerable<WebApplication.Models.ChuongTrinhDaoTao>

@{
    ViewBag.Title = "ListCTDaoTao";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title" style="font-family:Roboto">&emsp;CHƯƠNG TRÌNH ĐÀO TẠO</h4>
            <div class="page-title-right">
                <a href="@Url.Content("~/Models/ChuongTrinhDaoTao.xlsx")">
                    <button type="submit" id="button" name="button" value="Export" class="btn btn-secondary btn-rounded">
                        <i class="mdi mdi-microsoft-excel"></i> Template
                    </button>
                </a>
                <button type="button" id="button" name="button" value="Upload" class="btn btn-secondary btn-rounded" data-toggle="modal" data-target="#exampleModal" onclick="Clearform()">
                    <i class="mdi mdi-microsoft-excel"></i> Import
                </button>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->
<div class="row">
    <div class="col-xl-12">
        <div class="card-box taskboard-box">
            <ul class="sortable-list list-unstyled taskList" id="upcoming">
                @foreach (var item in Model)
                {
                    <li style="background-color:lightcyan">
                        <div class="kanban-box">
                            <div class="kanban-detail">
                                <h5 class="mt-0" style="font-family: Roboto"><a href="@Url.Action("ChiTietCTDaoTao", new { id = item.ID })" style="color: black">CTĐT Ngành @item.NganhDaoTao.Nganh - Khóa @item.KhoaDaoTao.Khoa</a></h5>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel" style="font-family: Roboto;">Thêm mới chương trình đào tạo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("UploadCTDaoTao", "ChuongTrinhDaoTao", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Khóa:</label>
                        <select class="form-control" name="Khoa">
                            @foreach (var khoa in ViewData["KhoaDaoTao"] as List<WebApplication.Models.KhoaDaoTao>)
                            {
                                <option value="@khoa.Khoa" selected>Khóa @khoa.Khoa</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Ngành:</label>
                        <select class="form-control" name="Nganh">
                            @foreach (var nganh in ViewData["NganhDaoTao"] as List<WebApplication.Models.NganhDaoTao>)
                            {
                                <option value="@nganh.Nganh">Ngành @nganh.Nganh</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Học kỳ bắt đầu:</label>
                        <select class="form-control" name="HocKy">
                            @foreach (var hocky in ViewData["HocKyDaoTao"] as List<WebApplication.Models.HocKyDaoTao>)
                            {
                                <option value="@hocky.HocKy">@hocky.HocKy</option>
                            }
                        </select>
                    </div>
                    <div class="file-upload-wrapper">
                        <div class="file-upload-wrapper">
                            <input id="excel_file" type="file" name="UploadedFile" class="dropify" required accept=".xls,.xlsx" onclick="Clearform()" />
                        </div>
                        <div id="excel_data" class="table-responsive"></div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Đóng" />
                        <input type="submit" class="btn btn-primary" value="Tải lên" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WebApplication/Areas/Faculty/Views/ChuongTrinhDaoTao/UploadCTDT.cshtml
@{
    Layout = null;
    var test = ViewData["test"] as WebApplication.Models.ChuongTrinhDaoTao;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UploadCTDT</title>
</head>
<body>
    <div>
        @test.HocKyDaoTao m @test.NganhDaoTao.Nganh m @test.KhoaDaoTao.Khoa
    </div>
</body>
</html>