WebApplication/Areas/Faculty/Controllers/DanhSachSinhVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.Data;
using System.Data.Entity;
using System.Net;
using OfficeOpenXml;

namespace WebApplication.Areas.Faculty.Controllers
{
    public class DanhSachSinhVienController : Controller
    {
        public Cap24 db = new Cap24();

        public static string RemoveUnicode(string text)
        {
            string[] arr1 = new string[] { "á", "à", "ả", "ã", "ạ", "â", "ấ", "ầ", "ẩ", "ẫ", "ậ", "ă", "ắ", "ằ", "ẳ", "ẵ", "ặ",
                "đ",
                "é","è","ẻ","ẽ","ẹ","ê","ế","ề","ể","ễ","ệ",
                "í","ì","ỉ","ĩ","ị",
                "ó","ò","ỏ","õ","ọ","ô","ố","ồ","ổ","ỗ","ộ","ơ","ớ","ờ","ở","ỡ","ợ",
                "ú","ù","ủ","ũ","ụ","ư","ứ","ừ","ử","ữ","ự",
                "ý","ỳ","ỷ","ỹ","ỵ",};
            string[] arr2 = new string[] { "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a",
                "d",
                "e","e","e","e","e","e","e","e","e","e","e",
                "i","i","i","i","i",
                "o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o","o",
                "u","u","u","u","u","u","u","u","u","u","u",
                "y","y","y","y","y",};
            for (int i = 0; i < arr1.Length; i++)
            {
                text = text.Replace(arr1[i], arr2[i]);
                text = text.Replace(arr1[i].ToUpper(), arr2[i].ToUpper());
            }
            return text;
        }
        public ActionResult TimKiemSinhVien(string texttimkiem)
        {
            var model = db.SinhViens.ToList();
            if (texttimkiem == null)
            {
                return View(model);
            }
            var text = RemoveUnicode(texttimkiem);
            var ho = "";
            var ten = "";
            var splittext = text.Split(' ');
            if (splittext.Length == 1)
            {
                ten = splittext[0];
            }
            else
            {
                ten = splittext[splittext.Length - 1];
                ho = splittext[0];
                for (int i = 1; i < splittext.Length - 1; i++)
                    ho += " " + splittext[i];
            }
            if (ten != "")
            {
                model = model.Where(p => RemoveUnicode(p.Ten.ToLower()) == ten.ToLower()).ToList();
            }
            if (ho != "")
            {
                model = model.Where(p => RemoveUnicode(p.Ho.ToLower()).Contains(ho.ToLower())).ToList();
            }
            var checkmssv = db.SinhViens.Where(p => p.MSSV.ToLower().Contains(texttimkiem.ToLower())).ToList();
            if (checkmssv != null)
                foreach (var item in checkmssv)
                    model.Add(item);
                ViewBag.Keyword = texttimkiem;
            return View(model);
        }

        //test Github
        public string KiemTraLop(string tenLop)
        {
            string ListLoi = "";

            if (tenLop.Length > 20)
            {
                ListLoi += "<p> Tên lớp không được quá 20 ký tự, số ký tự của lớp bạn nhập là: " + tenLop.Length + "</p>";
            }
            var listDBLop = db.LopQuanLies.ToList();
            var listLop = new List<string>();
            foreach (var item in listDBLop)
            {
                listLop.Add(item.TenLop);
            }
            if (CheckTonTai(tenLop, listLop))
            {
                ListLoi += "<p> Lớp đã tồn tại trong hệ thống, vui lòng thử lại!</p>";
            }
            return ListLoi;
        }
        public bool CheckTonTai(string element, List<string> list)
        {
            foreach (var item in list)
            {
                if (element == item)
                {
                    return true;
                }
            }
            return false;
        }
        public ActionResult ListLop()
        {
            var lopQuanLies = db.LopQuanLies.Include(l => l.KhoaDaoTao).Include(l => l.NganhDaoTao);
            return View(lopQuanLies.ToList());
        }
        // GET: Faculty/LopQuanLies/Create
        public ActionResult TaoMoiLop()
        {
            ViewBag.ID_Khoa = new SelectList(db.KhoaDaoTaos, "ID", "ID");
            ViewBag.ID_Nganh = new SelectList(db.NganhDaoTaos, "ID", "Nganh");
            return View();
        }

        public ActionResult Details(int ID)
        {
            var model = db.SinhViens.Find(ID);
            if (model == null)
            {
                return HttpNotFound();

            }
            return View(model);
        }
        public ActionResult KhoaSinhVien()
        {
            var lop = db.LopQuanLies.ToList();
            var khoa = new List<KhoaDaoTao>();
            var stringkhoa = new List<string>();
            foreach (var item in lop)
            {
                if (!CheckTonTai(item.KhoaDaoTao.Khoa.ToString(), stringkhoa))
                {
                    khoa.Add(item.KhoaDaoTao);
                    stringkhoa.Add(item.KhoaDaoTao.Khoa.ToString());
                }
            }
            return View(khoa);
        }

        public ActionResult NganhSinhVien(int ID)
        {
            var khoa = db.KhoaDaoTaos.Find(ID);
            var lop = db.LopQuanLies.Where(s => s.KhoaDaoTao.ID == khoa.ID).ToList();
            var nganh = new List<NganhDaoTao>();
            var stringnganh = new List<string>();
            if (lop != null)
                foreach (var item in lop)
                {
                    if (!CheckTonTai(item.NganhDaoTao.Nganh, stringnganh))
                    {
                        nganh.Add(item.NganhDaoTao);
                        stringnganh.Add(item.NganhDaoTao.Nganh);
                    }
                }
            ViewData["KhoaDaoTao"] = khoa;
            return View(nganh);
        }
        public ActionResult LopSinhVien(int idnganh, int idkhoa)
        {
            var khoa = db.KhoaDaoTaos.Find(idkhoa);
            var nganh = db.NganhDaoTaos.Find(idnganh);
            var lop = db.LopQuanLies.Where(s => s.NganhDaoTao.ID == idnganh).Where(s => s.KhoaDaoTao.ID == idkhoa).ToList();
            return View(lop);
        }
        // GET: Faculty/DanhSachSinhVien
        public ActionResult ListSinhVien(int id)
        {
            var sinhvien = db.SinhViens.OrderBy(s => s.TinhTrang.DoUuTien).Where(s => s.LopQuanLy.ID == id).ToList();
            return View(sinhvien);
        }
        public string KiemTraFile(HttpPostedFileBase file)
        {
            string DanhSachLoi = "";
            byte[] fileBytes = new byte[file.ContentLength];
            var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
            using (var package = new ExcelPackage(file.InputStream))
            {
                var currentSheet = package.Workbook.Worksheets;
                var workSheet = currentSheet.First();
                if (workSheet.Dimension != null)
                {
                    var noOfRow = workSheet.Dimension.End.Row;
                    var noOfCol = workSheet.Dimension.End.Column;
                    if (noOfCol == 15 && noOfRow > 1)
                    {
                        var listMSSV = new List<string>();
                        var listEmail = new List<string>();
                        for (int rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                        {
                            if (workSheet.Cells[rowIterator, 1].Value != null)
                            {
                                var MSSV = workSheet.Cells[rowIterator, 1].Value.ToString();
                                if (CheckTonTai(MSSV, listMSSV))
                                {
                                    DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột A: Dữ liệu bị trùng, dữ liệu trùng: " + MSSV + "</p>";
                                }
                                if (MSSV.Length > 20)
                                {
                                    DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột A: Dữ liệu không được quá 20 ký tự, số ký tự của " + MSSV + " là " + MSSV.Length + "<p>";
                                }
                                if (MSSV.Replace(" ", string.Empty) == null)
                                {
                                    DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột A: Dữ liệu không được để trống <p>";
                                }
                                listMSSV.Add(MSSV);
                            }
                            else
                            {
                                DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột A: Dữ liệu không được để trống <p>";
                            }
                            if (workSheet.Cells[rowIterator, 2].Value != null)
                            {
                                var Ho = workSheet.Cells[rowIterator, 2].Value.ToString();
                                if (Ho.Length > 100)
                                {
                                    DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột B: Dữ liệu không được quá 100 ký tự, số ký tự của " + Ho + " là " + Ho.Length + "<p>";
                                }
                                if (Ho.Replace(" ", string.Empty) == null)
                                {
                                    DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột B: Dữ liệu không được để trống <p>";
                                }
                            }
                            else
                            {
                                DanhSachLoi += "<p> Lỗi ở dòng " + rowIterator + ", cột B: Dữ liệu không được để trống <p>";
                            }
                            if (workSheet.Cells[rowIterator, 3].Value != null)
                            {

WebApplication/Areas/Faculty/Views/DanhSachSinhVien/KhoaSinhVien.cshtml
@model IEnumerable<WebApplication.Models.KhoaDaoTao>

@{
    ViewBag.Title = "KhoaSinhVien";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title" style="font-family:Roboto">DANH SÁCH SINH VIÊN</h4>
            <div class="page-title-right">
                <form>
                    <input type="text" class="btn btn-primary btn-rounded" placeholder="Tìm kiếm..." name="texttimkiem" style="background-color:white; color: black" />
                    <button type="submit" class="btn btn-secondary btn-rounded" formaction="@Url.Action("TimKiemSinhVien")"><i class="fas fa-search"></i>Tìm kiếm</button>
                    <input type="file" id="file" style="display:none;" />
                    <button type="button" class="btn btn-secondary btn-rounded" data-toggle="modal" data-target="#exampleModal">
                        <i class="mdi mdi-microsoft-excel"></i> Import
                    </button>
                    <button type="submit" formaction="@Url.Action("XuatDSSV")" value="" class="btn btn-secondary btn-rounded"><i class="mdi mdi-microsoft-excel"></i> Export</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->
<div class="row">
    <div class="col-xl-6">
        <div class="card-box taskboard-box">
            <ul class="sortable-list list-unstyled taskList" id="upcoming">
                @foreach (var item in Model)
                {
                    <li>
                        <div class="kanban-box">
                            <div class="kanban-detail">
                                <form>
                                    <a value="@item.Khoa" type="button" class="badge badge-danger float-right" href="@Url.Action("XacNhanXoaKhoa", new { id = item.ID })" style="color: white;"><i class="fas fa-times"></i></a>
                                    <h4 class="mt-0"><a href="@Url.Action("NganhSinhVien", new { id = item.ID })" class="text-dark">Danh sách sinh viên Khóa @item.Khoa</a></h4>
                                </form>
                            </div>
                        </div>
                    </li>
                }
            </ul>
            <!-- Modal -->
            <div class="modal fade" id="ModelXoaKhoaSV" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" style="font-family: Roboto;">Xóa danh sách sinh viên</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid text-center">
                                Xác nhận xóa Danh sách sinh viên
                            </div>
                            <div for="recipient-name" class="col-form-label">Nhập "Danh sách sinh viên Khóa @Session["KhoaSV"]" để xác nhận xóa:</div>
                            <input type="text" class="form-control" id="text" onchange="GetText(this.value)" value="" placeholder="Danh sách sinh viên Khóa @Session["KhoaSV"]">
                            <input id="textXacNhan" value="Danh sách sinh viên Khóa @Session["KhoaSV"]" hidden />
                        </div>
                        <div class="modal-footer">
                            <form method="post">
                                <input type="number" name="IDKhoa" value="@Session["KhoaSV"]" hidden />
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                <button type="submit" formaction="@Url.Action("XoaKhoaSV", new { IDKhoa = Session["KhoaSV"]})" id="XacNhanBtn" class="btn btn-primary" disabled>Xóa</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
           
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel" style="font-family: Roboto;">Thêm mới danh sách sinh viên</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            @using (Html.BeginForm("UpdateSinhVien", "DanhSachSinhVien", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <div class="file-upload-wrapper">
                                    <div class="file-upload-wrapper">
                                        <input type="file" value="@TempData["file"]" id="file_excel" name="UploadedFile" class="dropify" required accept=".xls,.xlsx" onclick="Clearform()" />
                                    </div>
                                    <div id="excel_data" class="table-responsive"></div>
                                </div>
                                <div class="modal-footer">
                                    <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Đóng" />
                                    <input type="submit" class="btn btn-secondary" value="Xem trước" formmethod="post" formaction="@Url.Action("XemTruocThongKe", "DanhSachSinhVien", new { enctype = "multipart/form-data" })" />
                                    <input type="submit" class="btn btn-primary" value="Tải lên" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="ModelCheckFile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel" style="font-family: Roboto;">Thêm mới danh sách sinh viên</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div>
                                @Html.Raw(Session["ThongBao"])
                            </div>
                            <div class="modal-footer">
                                <form action="@Url.Action("UpdateSinhVien")" method="post">
                                    <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Đóng" />
                                    <input type="submit" class="btn btn-primary" value="Tải lên" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- end col -->
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@if (Session["ThongBao"] != null)
{
    <script>
        $(document).ready(function () {
            $('#ModelCheckFile').modal('show');
        });
    </script>
}
@if (Session["KhoaSV"] != null)
{
    <script>
        $(document).ready(function () {
            $('#ModelXoaKhoaSV').modal('show');
        });
    </script>
    Session["KhoaSV"] = null;
}
<script>
    $('#ModelCheckFile').on('show.bs.modal', event => {
        var button = $(event.relatedTarget);
        var modal = $(this);
    });
</script>
<script>
    function GetText(val) {
        var text = document.getElementById("textXacNhan").value;
        if (val != text) {
            document.getElementById("XacNhanBtn").disabled = true;
        } else {
            document.getElementById("XacNhanBtn").disabled = false;
        }
    }
</script>
<script>
    function sortTable() {
        var tables, sort, i, x, y, tableSort;
        tables = document.getElementById("SortmyTable");
        sort = true;
        while (sort) {
            sort = false;
            tblrow = tables.rows;
            for (i = 1; i < (tblrow.length - 1); i++) {
                tableSort = false;
                x = tblrow[i].getElementsByTagName("td")[n];
                y = tblrow[i + 1].getElementsByTagName("td")[n];
                if (x.innerHTML.toUpperCase() > y.innerHTML.toUpperCase()) {
                    tableSort = true;
                    break;
                }
            }
            if (tableSort) {
                tblrow[i].parentNode.insertBefore(tblrow[i + 1], tblrow[i]);
                sort = true;
            }
        }
    }
</script>

WebApplication/Areas/Faculty/Views/DanhSachSinhVien/ListLop.cshtml
@model IEnumerable<WebApplication.Models.LopQuanLy>

@{
    ViewBag.Title = "ListLop";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
    int STT = 0;
}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title" style="font-family:Roboto">DANH SÁCH LỚP</h4>
            <div class="page-title-right">
                <!-- <div class="container">
                    <input type="text" id="search" placeholder="Search..." style="color: black;">
                    <div class="search"></div>
                </div> -->
                <button type="submit" id="button" formaction="@Url.Action("TaoMoiLop")" class="btn btn-secondary btn-rounded">
                    Tạo mới
                </button>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive text-nowrap">
                    <table class="table table-striped mb-0 dt-responsive">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tên lớp</th>
                                <th>Chủ nhiệm lớp</th>
                                <th>Khóa</th>
                                <th>Ngành</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                STT++;
                                <tr>
                                    <td>@STT</td>
                                    <td id="idLop">@item.TenLop</td>
                                    <td>
                                        @if (@item.ChuNhiem != null)
                                        {
                                            <a href="@Url.Action("LuuChuNhiem", new { id = item.ID})">
                                                @item.ChuNhiem
                                            </a>
                                        }
                                        else
                                        {
                                            <a style="color:red" href="@Url.Action("LuuChuNhiem", new { id = item.ID})">
                                                Trống
                                            </a>
                                        }
                                        <td>
                                        <span>K</span>@item.KhoaDaoTao.Khoa
                                    </td>
                                    <td>@item.NganhDaoTao.Nganh</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div> <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div> <!-- end row -->
<!-- Modal -->
<div class="modal fade" id="luuChuNhiem" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    @{ var lop = Session["Lop"] as WebApplication.Models.LopQuanLy; }
    @if (lop != null)
    {
        <form method="post">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" style="font-family: Roboto">Sửa giảng viên lớp @lop.TenLop</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <input hidden type="number" name="idLop" value="@lop.ID" required/>
                            <input class="form-control" type="email" id="chunhiem" name="chunhiem" value="@lop.ChuNhiem" required />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                        <button type="submit" class="btn btn-primary" formaction="@Url.Action("LuuChuNhiem")">Lưu</button>
                    </div>
                </div>
            </div>

        </form>

    }
</div>
<script>
    $('#luuChuNhiem').on('show.bs.modal', event => {
        var button = $(event.relatedTarget);
        var modal = $(this);
        // Use above variables to manipulate the DOM

    });
</script>
@if (Session["Lop"] != null)
{
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#luuChuNhiem').modal('show');
        });
    </script>
    Session["Lop"] = null;
}

WebApplication/Areas/Faculty/Views/DanhSachSinhVien/Search.cshtml
@model IEnumerable<WebApplication.Models.SinhVien>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/Faculty_Layout.cshtml";
    int STT = 0;
}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-sinhviens-center justify-content-between"
            <h4 class="page-title" style="font-family:Roboto">DANH SÁCH SINH VIÊN LỚP @Model.First().LopQuanLy.TenLop - NGÀNH @Model.First().LopQuanLy.NganhDaoTao.Nganh.ToUpper() KHÓA @Model.First().LopQuanLy.KhoaDaoTao.Khoa</h4>
            <div class="page-title-right">
                <div class="container">
                    <div class="hero__search__form">
                        <form action="@Url.Action("Search", "DanhSachSinhVien")" method="get">
                            <input type="text" name="Keyword" placeholder="Bạn tìm gì?" value="@ViewBag.Keyword">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                </div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-sinhvien"><a href="select-class.html"></a></li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive text-nowrap">
                    <table class="table table-striped mb-0 dt-responsive" id="table">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>MSSV</th>
                                <th>Họ</th>
                                <th>Tên</th>
                                <th>Ngày sinh</th>
                                <th>Giới tính</th>
                                <th>Tình trạng</th>
                                <th>Email_1</th>
                                <th>Email_2</th>
                                <th>Điện thoại di động</th>
                                <th>ĐTDĐ của cha</th>
                                <th>ĐTDĐ của mẹ</th>
                                <th>Địa chỉ thường trú</th>
                            </tr>
                        </thead>
                        <tbody id="table">
                            @foreach (var sinhvien in Model)
                            {
                                STT++;
                                <tr>
                                    <td>@STT</td>
                                    <td>@sinhvien.MSSV</td>
                                    <td>@sinhvien.Ho</td>
                                    <td>@sinhvien.Ten</td>
                                    <td>@sinhvien.NgaySinh</td>
                                    <td>@sinhvien.GioiTinh</td>
                                    <td>@sinhvien.TinhTrang.TenTinhTrang</td>
                                    <td>@sinhvien.Email_1</td>
                                    <td>@sinhvien.Email_2</td>
                                    <td>@sinhvien.DTDD</td>
                                    <td>@sinhvien.DTCha</td>
                                    <td>@sinhvien.DTMe</td>
                                    <td>@sinhvien.DiaChi</td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div> <!-- end .table-responsive-->
            </div> <!-- end card-body -->
        </div> <!-- end card -->
    </div> <!-- end col -->
</div> <!-- end row -->

WebApplication/Areas/Faculty/Views/DanhSachSinhVien/XoaLop.cshtml
@model WebApplication.Models.LopQuanLy

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LopQuanLy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenLop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuNhiem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuNhiem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhoaDaoTao.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhoaDaoTao.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NganhDaoTao.Nganh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NganhDaoTao.Nganh)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListLop")
        </div>
    }
</div>